# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QSBpPrvZmd3e9ciQz9OEvHiB7Jj85P9a
"""

import pickle

def salvar_contatos(contatos, arquivo='contatos.pkl'):
    with open(arquivo, 'wb') as f:
        pickle.dump(contatos, f)
    print("Contatos salvos com sucesso!")

def carregar_contatos(arquivo='contatos.pkl'):
    try:
        with open(arquivo, 'rb') as f:
            contatos = pickle.load(f)
        print("Contatos carregados com sucesso!")
    except FileNotFoundError:
        contatos = []
        print("Nenhum contato encontrado. Criando um novo arquivo.")
    return contatos

def adicionar_contato(contatos):
    nome = input("Digite o nome do contato: ")
    telefone = input("Digite o telefone do contato: ")
    contato = {"nome": nome, "telefone": telefone}
    contatos.append(contato)
    print("Contato adicionado com sucesso!")

def procurar_contato(contatos):
    nome = input("Digite o nome do contato que deseja procurar: ")
    for contato in contatos:
        if contato["nome"].lower() == nome.lower():
            print(f"Nome: {contato['nome']}, Telefone: {contato['telefone']}")
            break
    else:
        print("Contato não encontrado.")

def listar_contatos(contatos):
    if contatos:
        print("Lista de contatos:")
        for contato in contatos:
            print(f"Nome: {contato['nome']}, Telefone: {contato['telefone']}")
            print("")
    else:
        print("Não há contatos salvos.")

def main():
    contatos = carregar_contatos()
    print('='*19)
    print('Agenda de Contatos')
    print('='*19)
    while True:
        print("1. Adicionar contato")
        print("2. Procurar contato")
        print("3. Listar todos os contatos")
        print("4. Sair")
        opcao = input("Escolha uma opção: ")

        if opcao == "1":
            adicionar_contato(contatos)
        elif opcao == "2":
            procurar_contato(contatos)
        elif opcao == "3":
            listar_contatos(contatos)
        elif opcao == "4":
            salvar_contatos(contatos)
            print("Saindo do programa...")
            break
        else:
            print("Opção inválida. Tente novamente.")

main()